### PR TITLE
Roof parks mount

### PR DESCRIPTION
**Pull request by LuckyEddie47**
PR to address issue #17.
Added ROOF_CLOSE_PARKS_MOUNT.
Added MOUNT_PARK_TIMEOUT as 30 - 240 seconds. Allows for mount with 1°/sec slew plus a minute for ramp up/down/tolerance.
Added validation for new options.
Added parked polling task and function as suggested.
Changed the stop function to additional cancel a close waiting for mount park.
Moved already closed check to top of close function.
Added safety override option into interlock checks on both open and close functions. Existing comments suggest these should have already had this and it makes sense to me.
Added new roof error and status.

Unrelated - removed the additional lower case #include "Tca9555.h"

I made the momentary relay close to signal the mount to park a 2 second duration. I'm assuming this is long enough for OnStep to definitely poll for the signal on any supported MCU but though I'd mention it just in case.

### CODE REVIEW

**Comment by hjd1964** [comment]
OnStepX checks the park signal once a second.  That doesn't mean it will successfully begin a park within one second though.  For example X could be in the middle of a goto or a guide which will cause it to ignore the park request.  I'd hold the park signal high for the entire MOUNT_PARK_TIMEOUT period or until you get the signal that the park succeeded.

**Comment by hjd1964** [comment]
I'd also like to simplify some of the new roof.cpp code so check to see if it all still works as expected and let me know.  Should be ok, exactly the same logic, if I don't mess up, just refactoring.

**Comment by LuckyEddie47** [comment]
While you're in there, I just found the following  when I synced my fork:
Config.h has lost the #define AXIS1_ENCODER on commit #b022aec
EthernetManager.h & Serial_IP_Ethernet.h now both reference EthernetX.h instead of Ethernet.h
I had to revert these three in order to compile.

**Comment by hjd1964** [comment]
>Config.h has lost the #define AXIS1_ENCODER on commit #b022aec

Taken care of, thanks.

**Comment by hjd1964** [comment]
EthernetManager.h & Serial_IP_Ethernet.h now both reference EthernetX.h instead of Ethernet.h
I had to revert these three in order to compile.

I reverted that change and updated my Ethernet library so its based on Arduino Ethernet 2.0.2...
My library is required if you want Ethernet W5500 support while running on an ESP32.  It's also required if you want ASCOM Alpaca to work correctly.

**Comment by hjd1964** [comment]
>EthernetManager.h & Serial_IP_Ethernet.h now both reference EthernetX.h instead of Ethernet.h
>I had to revert these three in order to compile.

There's a long story concerning the decision of what to name my library (keeping Arduino IDE v2.x from recommending upgrade back to upstream) and for when to use my library (ESP32 and ASCOM Alpaca) or the stock Arduino library or the Ethernet2 library (for ESP8266 which I suspect isn't needed now so perhaps that #ifdef ESP8266 should be removed?)

**Comment by LuckyEddie47** [comment]
Ah ha, the penny drops. Thank you Howard.

**Pull request merged**
